### ISSUE TITLE
Where would I learn?

### ISSUE THREAD

**Issue by 12944qwerty** [BonfireScratch/learn-c#2]
Where do I learn c here? I am really confused with this.....
I really want to learn c.

**Comment by BonfireScratch** [comment]
@12944qwerty you basically read other people's code. This is how I learnt Python and TypeScrpt

**Comment by 12944qwerty** [comment]
ah :)

**Comment by BonfireScratch** [comment]
@12944qwerty do you want me to create step-by-step tutorials? (it would be a bit hard because I'm learning C right now)

**Comment by 12944qwerty** [comment]
I would prefer it. If it's hard for you, you don't have to.
